### ISSUE TITLE
Error on docker build

### ISSUE THREAD

**Issue by erasta** [argosp/argos#30]
adding a volume on docker-compose.yml on this commit https://github.com/argosp/argos/commit/35948d9b0bbd19fa5285290105b8f95cec04c340 resulted with docker build error:
```
ERROR: Duplicate mount points: [/Users/<username>/Code/argos/trialgraph:/usr/src/app:rw, /Users/<username>/Code/argos/uploads:/usr/src/app:rw]
```
reverting to previous commit fixes this.
@adishua @YehuditGrinwald

**Comment by YehuditGrinwald** [comment]
@erasta fixed and pushed
